folder: ZG3.0
gcs_url: https://storage.googleapis.com/plode_resource/sdcard-assets/ZG3.0/ZG3.0.zip
last_commit: 8dadce37df2346fc07995e3947cdb0cec5449ef3
last_updated: '2025-11-17T07:33:24.479771+00:00'
version: 1.2
zip_file: ZG3.0.zip
