folder: ZG2.2
gcs_url: https://storage.googleapis.com/plode_resource/sdcard-assets/ZG2.2/ZG2.2.zip
last_commit: bae0f93ee2f1a9ac48ad7301af99d3d5e35149a5
last_updated: '2026-06-24T08:15:15.417679+00:00'
version: 2.1
zip_file: ZG2.2.zip
