folder: ZG2.2
gcs_url: https://storage.googleapis.com/plode_resource/sdcard-assets/ZG2.2/ZG2.2.zip
last_commit: cbd9ef84196f53f507911213e866bb2fbf3ab8b7
last_updated: '2026-04-15T05:20:48.676070+00:00'
version: 1.1
zip_file: ZG2.2.zip
