folder: ZG2.0
gcs_url: https://storage.googleapis.com/plode_resource/sdcard-assets/ZG2.0/ZG2.0.zip
last_commit: 1ddef238bcd90394f315544bac7ba0312d6c821e
last_updated: '2025-11-17T06:02:16.526470+00:00'
version: 1.4
zip_file: ZG2.0.zip
