folder: ZG2.0
gcs_url: https://storage.googleapis.com/plode_resource/sdcard-assets/ZG2.0/ZG2.0.zip
last_commit: dc48eca4cb613c6dbcab3447e7cf0b09ce8f04c1
last_updated: '2026-06-26T09:13:59.328526+00:00'
version: 5.2
zip_file: ZG2.0.zip
