folder: ZG2.1
gcs_url: https://storage.googleapis.com/plode_resource/sdcard-assets/ZG2.1/ZG2.1.zip
last_commit: ed9b2b07ad63b79b2fbcfd7c082cdf2a5b7869fc
last_updated: '2026-06-26T08:53:25.198002+00:00'
version: 2.1
zip_file: ZG2.1.zip
