folder: ZG2.1
gcs_url: https://storage.googleapis.com/plode_resource/sdcard-assets/ZG2.1/ZG2.1.zip
last_commit: 61cca03382929c3afee5a5e1f2b7f836120e9de0
last_updated: '2026-06-26T09:00:43.316318+00:00'
version: 2.5
zip_file: ZG2.1.zip
