folder: ZG2.1
gcs_url: https://storage.googleapis.com/plode_resource/sdcard-assets/ZG2.1/ZG2.1.zip
last_commit: dbc3631a3eb95ecd6a0851cbea4c37bb38257780
last_updated: '2026-02-19T05:33:57.025387+00:00'
version: 1.7
zip_file: ZG2.1.zip
